name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to cPanel using API token
        uses: pinkasey/cpanel-deploy-action@v1.2.1
        with:
          hostname: ${{ secrets.CPANEL_HOST }}
          cpanelApiPort: 2083
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          repository_root: ${{ secrets.CPANEL_REPOSITORY_ROOT }}
          updateRepository: true
          branch: main
