name: Deploy to cPanel

on:
  push:
    branches:
      - main  

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.CPANEL_HOST }}     
          ftp-username: ${{ secrets.CPANEL_USERNAME }} 
          ftp-password: ${{ secrets.CPANEL_PASSWORD }} 
          local-dir: ./dist                             
          ftp-remote-dir: ${{ secrets.CPANEL_REPOSITORY_ROOT }}
