name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.2.1
        with:
          hostname: ${{ secrets.CPANEL_HOST }}          
          cpanelApiPort: 2083
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          repository_root: ${{ secrets.CPANEL_REPOSITORY_ROOT }}  
          updateRepository: true
          branch: main

      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
